In [1]:
import numpy as np

In [2]:
A = np.array([[1,0,0], [0,1,0], [0,0,1]]) #Input Array
B = np.array([[0,0,1], [0,1,0], [1,0,0]]) #Associated Vector

A1 = np.array([[0,0,1], [0,1,0], [1,0,0]]) #testing associative vector as input
A2 = np.array([[1,0,1], [1,1,0], [0,1,1]]) #two changes
A3 = np.array([[0,1,1], [1,0,1], [1,1,0]]) #incomplete

In [3]:
class BAM(object):
    def __init__(self):
            self.epoch = 3
    
    def activate(self, A):
        f = np.zeros((len(A),len(A)))
        for i in range(len(A[1])):
            for j in range(len(A[1])):
                
                if(A[i][j]==1):
                    f[i][j] = 1
                else:
                    f[i][j] = -1
        return f
    
    def getWeights(self, A, B):
        W = np.dot(self.activate(A), self.activate(B))
        return W
    
    def applyThreshold(self, A, W):
        threshold1 = np.dot(A,W)
        temp1 = np.zeros(len(threshold1))
        for i in range(len(temp1)):
            if(threshold1[i]<=0):
                temp1[i] = 0
            else:
                temp1[i] = 1
        print(f'forward:{A} ---> {threshold1} ---> {temp1}')
    
        threshold2 = np.dot(temp1,W.T)
        temp2 = np.zeros(len(threshold2))
        for i in range(len(temp2)):
            if(threshold2[i]<=0):
                temp2[i] = 0
            else:
                temp2[i] = 1
        print(f'backward:{temp1} ---> {threshold2} ---> {temp2}')
    
        return temp2
    
    
    def train(self, A, W):
        #print("Pass 1")
        Adelta = self.applyThreshold(A, W)
        #print("Epoch 2")
        Bdelta = self.applyThreshold(Adelta, W)
        #print("Epoch 3")
        self.applyThreshold(Bdelta, W)
        #print("\n")
        
    def main(self, A, B):
        W = BAM.getWeights(A,B)
        for i in range(len(A)):
            print("\nPattern", i+1, "\n")
            BAM.train(A[i], W)
        return W
    

In [4]:
BAM = BAM()

In [5]:
BAM.main(A, B)


Pattern 1 

forward:[1 0 0] ---> [-1. -1.  3.] ---> [0. 0. 1.]
backward:[0. 0. 1.] ---> [ 3. -1. -1.] ---> [1. 0. 0.]
forward:[1. 0. 0.] ---> [-1. -1.  3.] ---> [0. 0. 1.]
backward:[0. 0. 1.] ---> [ 3. -1. -1.] ---> [1. 0. 0.]
forward:[1. 0. 0.] ---> [-1. -1.  3.] ---> [0. 0. 1.]
backward:[0. 0. 1.] ---> [ 3. -1. -1.] ---> [1. 0. 0.]

Pattern 2 

forward:[0 1 0] ---> [-1.  3. -1.] ---> [0. 1. 0.]
backward:[0. 1. 0.] ---> [-1.  3. -1.] ---> [0. 1. 0.]
forward:[0. 1. 0.] ---> [-1.  3. -1.] ---> [0. 1. 0.]
backward:[0. 1. 0.] ---> [-1.  3. -1.] ---> [0. 1. 0.]
forward:[0. 1. 0.] ---> [-1.  3. -1.] ---> [0. 1. 0.]
backward:[0. 1. 0.] ---> [-1.  3. -1.] ---> [0. 1. 0.]

Pattern 3 

forward:[0 0 1] ---> [ 3. -1. -1.] ---> [1. 0. 0.]
backward:[1. 0. 0.] ---> [-1. -1.  3.] ---> [0. 0. 1.]
forward:[0. 0. 1.] ---> [ 3. -1. -1.] ---> [1. 0. 0.]
backward:[1. 0. 0.] ---> [-1. -1.  3.] ---> [0. 0. 1.]
forward:[0. 0. 1.] ---> [ 3. -1. -1.] ---> [1. 0. 0.]
backward:[1. 0. 0.] ---> [-1. -1.  3.] ---> 

array([[-1., -1.,  3.],
       [-1.,  3., -1.],
       [ 3., -1., -1.]])

In [6]:
A1 = np.array([[0,0,1], [0,1,0], [1,0,0]]) #testing associative vector as input
BAM.main(A1, B)


Pattern 1 

forward:[0 0 1] ---> [-1. -1.  3.] ---> [0. 0. 1.]
backward:[0. 0. 1.] ---> [-1. -1.  3.] ---> [0. 0. 1.]
forward:[0. 0. 1.] ---> [-1. -1.  3.] ---> [0. 0. 1.]
backward:[0. 0. 1.] ---> [-1. -1.  3.] ---> [0. 0. 1.]
forward:[0. 0. 1.] ---> [-1. -1.  3.] ---> [0. 0. 1.]
backward:[0. 0. 1.] ---> [-1. -1.  3.] ---> [0. 0. 1.]

Pattern 2 

forward:[0 1 0] ---> [-1.  3. -1.] ---> [0. 1. 0.]
backward:[0. 1. 0.] ---> [-1.  3. -1.] ---> [0. 1. 0.]
forward:[0. 1. 0.] ---> [-1.  3. -1.] ---> [0. 1. 0.]
backward:[0. 1. 0.] ---> [-1.  3. -1.] ---> [0. 1. 0.]
forward:[0. 1. 0.] ---> [-1.  3. -1.] ---> [0. 1. 0.]
backward:[0. 1. 0.] ---> [-1.  3. -1.] ---> [0. 1. 0.]

Pattern 3 

forward:[1 0 0] ---> [ 3. -1. -1.] ---> [1. 0. 0.]
backward:[1. 0. 0.] ---> [ 3. -1. -1.] ---> [1. 0. 0.]
forward:[1. 0. 0.] ---> [ 3. -1. -1.] ---> [1. 0. 0.]
backward:[1. 0. 0.] ---> [ 3. -1. -1.] ---> [1. 0. 0.]
forward:[1. 0. 0.] ---> [ 3. -1. -1.] ---> [1. 0. 0.]
backward:[1. 0. 0.] ---> [ 3. -1. -1.] ---> 

array([[ 3., -1., -1.],
       [-1.,  3., -1.],
       [-1., -1.,  3.]])

In [7]:
BAM.main(A2, B)


Pattern 1 

forward:[1 0 1] ---> [ 2. -2. -2.] ---> [1. 0. 0.]
backward:[1. 0. 0.] ---> [ 1. -3.  1.] ---> [1. 0. 1.]
forward:[1. 0. 1.] ---> [ 2. -2. -2.] ---> [1. 0. 0.]
backward:[1. 0. 0.] ---> [ 1. -3.  1.] ---> [1. 0. 1.]
forward:[1. 0. 1.] ---> [ 2. -2. -2.] ---> [1. 0. 0.]
backward:[1. 0. 0.] ---> [ 1. -3.  1.] ---> [1. 0. 1.]

Pattern 2 

forward:[1 1 0] ---> [-2. -2.  2.] ---> [0. 0. 1.]
backward:[0. 0. 1.] ---> [ 1.  1. -3.] ---> [1. 1. 0.]
forward:[1. 1. 0.] ---> [-2. -2.  2.] ---> [0. 0. 1.]
backward:[0. 0. 1.] ---> [ 1.  1. -3.] ---> [1. 1. 0.]
forward:[1. 1. 0.] ---> [-2. -2.  2.] ---> [0. 0. 1.]
backward:[0. 0. 1.] ---> [ 1.  1. -3.] ---> [1. 1. 0.]

Pattern 3 

forward:[0 1 1] ---> [-2.  2. -2.] ---> [0. 1. 0.]
backward:[0. 1. 0.] ---> [-3.  1.  1.] ---> [0. 1. 1.]
forward:[0. 1. 1.] ---> [-2.  2. -2.] ---> [0. 1. 0.]
backward:[0. 1. 0.] ---> [-3.  1.  1.] ---> [0. 1. 1.]
forward:[0. 1. 1.] ---> [-2.  2. -2.] ---> [0. 1. 0.]
backward:[0. 1. 0.] ---> [-3.  1.  1.] ---> 

array([[ 1., -3.,  1.],
       [-3.,  1.,  1.],
       [ 1.,  1., -3.]])

In [8]:
BAM.main(A3, B)


Pattern 1 

forward:[0 1 1] ---> [-2. -2.  2.] ---> [0. 0. 1.]
backward:[0. 0. 1.] ---> [-3.  1.  1.] ---> [0. 1. 1.]
forward:[0. 1. 1.] ---> [-2. -2.  2.] ---> [0. 0. 1.]
backward:[0. 0. 1.] ---> [-3.  1.  1.] ---> [0. 1. 1.]
forward:[0. 1. 1.] ---> [-2. -2.  2.] ---> [0. 0. 1.]
backward:[0. 0. 1.] ---> [-3.  1.  1.] ---> [0. 1. 1.]

Pattern 2 

forward:[1 0 1] ---> [-2.  2. -2.] ---> [0. 1. 0.]
backward:[0. 1. 0.] ---> [ 1. -3.  1.] ---> [1. 0. 1.]
forward:[1. 0. 1.] ---> [-2.  2. -2.] ---> [0. 1. 0.]
backward:[0. 1. 0.] ---> [ 1. -3.  1.] ---> [1. 0. 1.]
forward:[1. 0. 1.] ---> [-2.  2. -2.] ---> [0. 1. 0.]
backward:[0. 1. 0.] ---> [ 1. -3.  1.] ---> [1. 0. 1.]

Pattern 3 

forward:[1 1 0] ---> [ 2. -2. -2.] ---> [1. 0. 0.]
backward:[1. 0. 0.] ---> [ 1.  1. -3.] ---> [1. 1. 0.]
forward:[1. 1. 0.] ---> [ 2. -2. -2.] ---> [1. 0. 0.]
backward:[1. 0. 0.] ---> [ 1.  1. -3.] ---> [1. 1. 0.]
forward:[1. 1. 0.] ---> [ 2. -2. -2.] ---> [1. 0. 0.]
backward:[1. 0. 0.] ---> [ 1.  1. -3.] ---> 

array([[ 1.,  1., -3.],
       [ 1., -3.,  1.],
       [-3.,  1.,  1.]])