## Importing needed libraries

In [1]:
#Name: Parisa Suchdev
#collaborated with Anna Jane and Shaurya Swami

import numpy as np

## Input array

In [2]:
X = np.array([
    [0,0,0,0],
    [1,1,0,1],
    [1,0,1,0],
    
])

In [3]:
Test = np.array([
    [1,0,1,1], #should predict [1,0,1,0]
    [1,1,1,1], #should predict [1,1,0,1]
    [1,1,1,0], #should predict [1,0,1,0]
    
    [1,0,0,0], #should predict [1,0,1,0] or [0,0,0,0]
    [0,0,0,1], #should predict [0,0,0,0] or [0,0,0,0]
    [0,0,1,0] #should predict [1,0,1,0] or [0,0,0,0]
])

## Hopfield Network

In [5]:
class hopfieldNetwork(object):
    def __init__(self):
        self.n = X[0].size #getting size n to create weight matrix
        self.W = np.zeros((self.n,self.n)) #creating zeros weight matrix of size n
        self.savedW = self.learn(X) #saving the weights here because once calculated, they don't change
        
    #Creating learning rule
    def learningRule(self, v):
        self.f = np.zeros(len(v))
        for i in range(len(v)):
            if(v[i] == 1):
                self.f[i] = 1
            else:
                self.f[i] = -1
        return self.f
    
    #Learn Weights
    def learn(self, X):
        #passing input to the function
        function = []
        for i in range(len(X)):
            function.append(self.learningRule(X[i])) #passing it through the learn function to apply rules on input
        function = np.array(function)
        
        #Create Weight Matrix
        for i in range(len(self.W)):
            for j in range (i):
                self.W[i][j] = np.sum(function[:,i]*function[:,j])
                self.W[j][i] = np.sum(function[:,j]*function[:,i])
        return self.W
    
    #Weights should not change!
    
    #A part of performace rule is to multiply input with weights
    def getS(self, X):
        self.sum = np.dot(X, self.savedW)
        return self.sum
    
    #just getting the sum calculated ready to feed into performance rules
    def perform(self, X):
        gettingSum = self.getS(X)
        self.su = []
        for i in range(len(gettingSum)):
            self.su.append(self.performanceRules(gettingSum[i]))
        self.su = np.array(self.su)
        return self.su
    
    #creating the performance rules
    def performanceRules(self, s):
        self.rule1 = np.zeros(len(s))
        self.rule2 = np.zeros(len(s))
    
        #calculation for rule 1
        for i in range(len(s)):
            if(s[i] >= 0):
                self.rule1[i] = 1
            else:
                self.rule1[i] = 0
                
        #calculation for rule 2    
        for i in range(len(s)):
            if(s[i] > 0):
                self.rule2[i] = 1
            elif(s[i] < 0):
                self.rule2[i] = 0
            elif(s[i] == 0):
                self.rule2[i] = self.rule2[i]
        return {'Rule1':self.rule1, "Rule2":self.rule2}

In [6]:
HN = hopfieldNetwork()
print("Weight Matrix:\n",HN.learn(X))

Weight Matrix:
 [[ 0.  1.  1.  1.]
 [ 1.  0. -1.  3.]
 [ 1. -1.  0. -1.]
 [ 1.  3. -1.  0.]]


In [7]:
print("Original Input:\n", X)
print("Output Matrix:\n",HN.perform(X))

Original Input:
 [[0 0 0 0]
 [1 1 0 1]
 [1 0 1 0]]
Output Matrix:
 [{'Rule1': array([1., 1., 1., 1.]), 'Rule2': array([0., 0., 0., 0.])}
 {'Rule1': array([1., 1., 0., 1.]), 'Rule2': array([1., 1., 0., 1.])}
 {'Rule1': array([1., 1., 1., 1.]), 'Rule2': array([1., 0., 1., 0.])}]


In [10]:
print("Test Input:\n", Test)
print("""
    [1,0,1,1] #should ideally predict [1,0,1,0] @ 25% error
    [1,1,1,1] #should ideally predict [1,1,0,1] @ 25% error
    [1,1,1,0] #should ideally predict [1,0,1,0] @ 25% error
    
    [1,0,0,0] #should ideally predict [1,0,1,0] or [0,0,0,0]
    [0,0,0,1] #should ideally predict [0,0,0,0]
    [0,0,1,0] #should ideally predict [1,0,1,0] or [0,0,0,0]
""")
print("Output Matrix:\n",HN.perform(Test))

Test Input:
 [[1 0 1 1]
 [1 1 1 1]
 [1 1 1 0]
 [1 0 0 0]
 [0 0 0 1]
 [0 0 1 0]]

    [1,0,1,1] #should ideally predict [1,0,1,0] @ 25% error
    [1,1,1,1] #should ideally predict [1,1,0,1] @ 25% error
    [1,1,1,0] #should ideally predict [1,0,1,0] @ 25% error
    
    [1,0,0,0] #should ideally predict [1,0,1,0] or [0,0,0,0]
    [0,0,0,1] #should ideally predict [0,0,0,0]
    [0,0,1,0] #should ideally predict [1,0,1,0] or [0,0,0,0]

Output Matrix:
 [{'Rule1': array([1., 1., 1., 1.]), 'Rule2': array([1., 1., 0., 0.])}
 {'Rule1': array([1., 1., 0., 1.]), 'Rule2': array([1., 1., 0., 1.])}
 {'Rule1': array([1., 1., 1., 1.]), 'Rule2': array([1., 0., 0., 1.])}
 {'Rule1': array([1., 1., 1., 1.]), 'Rule2': array([0., 1., 1., 1.])}
 {'Rule1': array([1., 1., 0., 1.]), 'Rule2': array([1., 1., 0., 0.])}
 {'Rule1': array([1., 0., 1., 0.]), 'Rule2': array([1., 0., 0., 0.])}]
